# Generated by Django 5.2.4 on 2025-08-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='match_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='resume_name',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='user',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
