# Generated by Django 5.2.4 on 2025-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_match_score_matchresult_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='resume',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='resume_file',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
